### ISSUE TITLE
Стили в разделе управления гильдией

### ISSUE THREAD

**Issue by nkdmb** [VimeWorld/cabinet#11]
1. В личном кабинете в разделе управления гильдией, где можно писать свой "web_info" в темной теме цвет текста в поле для ввода сливается с фоном
2. При смене темы с темной на светлую не меняются стили поля для ввода, остаются с прошлой темы до обновления страницы, также и в обратную сторону со светлой темы на темную

https://youtu.be/-GqCB9cH-fo

**Comment by xtrafrancyz** [comment]
1. Исправлено
2. Простого решения для смены темы редактора без потери контента я не нашел. Проблема критичная, поэтому не хочется усложнять проект целым жизненным циклом для того редактора. Если будет хорошее и простое решение, то буду рад пулл реквесту
